version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/packages/use-disclosable" # Location of package manifests
    schedule:
      interval: "weekly"