name: Ci

on:
  release:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4

        - name: "Install pnpm"
          uses: pnpm/action-setup@v2
          with:
            version: 9
            run_install: false

        - name: Use Node.js
          uses: actions/setup-node@v4
          with:
            node-version: "20"

        - name: Install dependencies
          run: pnpm install --frozen-lockfile

        - name: Checks
          run: pnpm run check
        
        - name: Build
          run: pnpm run build --filter=use-disclosable

        - name: Test
          run: pnpm run test:single --filter=use-disclosable

        - name: Copy README
          run: cp README.md packages/use-disclosable/README.md
        
        - name: "Publish"
          run: pnpm publish --access public --no-git-checks --filter=use-disclosable
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}